apiVersion: v1
kind: Pod
metadata:
  name: tls-test
  labels:
    app: tls-test
spec:
  containers:
    - name: nginx
      image: songsogu/test-tls:latest
      ports:
        - containerPort: 8080
          name: http-web-svc