apiVersion: v1
kind: Service
metadata:
  name: tls-test-headless
spec:
  clusterIP: None
  selector:
    app: tls-test
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: http-web-svc
